name: Site Settings and Labels
type: module
description: Provides a site settings entity for non-admin controlled settings and labels
core: 8.x
core_version_requirement: ^8 || ^9
configure: site_settings.site_settings_config_form
package: Custom

# Information added by Drupal.org packaging script on 2020-05-23
version: '8.x-1.19'
project: 'site_settings'
datestamp: 1590234918
